language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"
  - "pypy3"

env:
  matrix:
   - REDIS="redis==2.9.1"
   - REDIS="redis==2.10.6"

install:
- "pip install $REDIS"
- "pip install ."

script: "python run_tests.py"

services:
  - redis-server
